pipeline {

    agent {
        label 'terraform'
    }

    parameters {

        choice(
            name: 'ENV',
            choices: ['dev', 'stage', 'prod'],
            description: 'Select Terraform Workspace'
        )

        choice(
            name: 'ACTION',
            choices: ['plan','apply','destroy'],
            description: 'Terraform Action'
        )

    }

    environment {

        BACKEND_DIR = "terraform-megha-project/backend"
        INFRA_DIR   = "terraform-megha-project/infra-app"

    }

    stages {

        stage('Clean Workspace') {
            steps {
                deleteDir()
            }
        }

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Verify Tools') {
            steps {

                sh '''
                terraform version
                aws --version
                git --version
                '''

            }
        }

        stage('Create Backend') {
            steps {
                dir('terraform-megha-project/backend') {
                    sh '''
                        terraform init -upgrade=false

                        aws s3api head-bucket \
                          --bucket terraform-megha-project-tfstate \
                          >/dev/null 2>&1

                        S3_EXISTS=$?

                        aws dynamodb describe-table \
                          --table-name terraform-megha-project-locks \
                          >/dev/null 2>&1

                        DDB_EXISTS=$?

                        if [ "$S3_EXISTS" -eq 0 ] && [ "$DDB_EXISTS" -eq 0 ]; then
                            echo "Backend already exists. Skipping creation."
                        else
                            terraform apply -auto-approve
                        fi
                    '''
                }
            }
        }

        stage('Terraform Init') {

            steps {

                dir("${INFRA_DIR}") {

                    sh """
                    terraform init \
                    -backend-config=../backend/${params.ENV}.hcl \
                    -reconfigure \
                    -upgrade=false
                    """

                }

            }

        }

        stage('Workspace') {

            steps {

                dir("${INFRA_DIR}") {

                    sh """
                    terraform workspace select ${params.ENV} || terraform workspace new ${params.ENV}
                    terraform workspace show
                    """

                }

            }

        }

        stage('Validate') {

            steps {

                dir("${INFRA_DIR}") {

                    sh '''
                    terraform validate
                    terraform fmt -check
                    '''

                }

            }

        }

        stage('Terraform Plan') {

            when {

                anyOf {

                    expression { params.ACTION=="plan" }
                    expression { params.ACTION=="apply" }

                }

            }

            steps {

                dir("${INFRA_DIR}") {

                    sh """
                    terraform plan \
                    -var-file=terraform.tfvars \
                    -out=tfplan \
                    -input=false
                    """

                }

            }

        }

        stage('Approval') {

            when {

                expression {

                    params.ACTION=="apply"

                }

            }

            steps {

                input "Deploy ${params.ENV} Infrastructure?"

            }

        }

        stage('Terraform Apply') {

            when {

                expression {

                    params.ACTION=="apply"

                }

            }

            steps {

                dir("${INFRA_DIR}") {

                    sh '''
                    terraform apply -auto-approve tfplan
                    '''

                }

            }

        }

        stage('Terraform Destroy') {

            when {

                expression {

                    params.ACTION=="destroy"

                }

            }

            steps {

                dir("${INFRA_DIR}") {

                    sh """
                    terraform workspace select ${params.ENV}

                    terraform destroy \
                      -var-file=terraform.tfvars \
                      -auto-approve \
                      -input=false
                    """

                }

            }

        }

    }

    post {

        success {

            echo "Deployment Successful"

            withCredentials([string(credentialsId: 'terraform-slack-webhook', variable: 'SLACK_URL')]) {

                sh """
                curl -X POST \
                -H 'Content-Type: application/json' \
                --data '{
                  "text":"✅ Terraform ${params.ACTION} SUCCESS

Environment : ${params.ENV}
Job         : ${env.JOB_NAME}
Build       : #${env.BUILD_NUMBER}
URL         : ${env.BUILD_URL}"
                }' \
                \$SLACK_URL
                """
            }

        }

        failure {

            echo "Deployment Failed"

            withCredentials([string(credentialsId: 'terraform-slack-webhook', variable: 'SLACK_URL')]) {

                sh """
                curl -X POST \
                -H 'Content-Type: application/json' \
                --data '{
                  "text":"❌ Terraform ${params.ACTION} FAILED

Environment : ${params.ENV}
Job         : ${env.JOB_NAME}
Build       : #${env.BUILD_NUMBER}
URL         : ${env.BUILD_URL}"
                }' \
                \$SLACK_URL
                """
            }

        }

        always {

            archiveArtifacts artifacts: '**/tfplan', allowEmptyArchive: true
            deleteDir()

        }

    }

}
