pipeline {

    agent {
        label 'terraform'
    }

    parameters {

        choice(
            name: 'ENV',
            choices: ['dev', 'stage', 'prod'],
            description: 'Select Terraform Workspace'
        )

        choice(
            name: 'ACTION',
            choices: ['plan','apply','destroy'],
            description: 'Terraform Action'
        )

    }

    environment {

        BACKEND_DIR = "terraform-megha-project/backend"
        INFRA_DIR   = "terraform-megha-project/infra-app"

    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Verify Tools') {
            steps {

                sh '''
                terraform version
                aws --version
                git --version
                '''

            }
        }

        stage('Create Backend') {

            steps {

                dir("${BACKEND_DIR}") {

                    sh """
                        terraform init
                        terraform validate
                        terraform apply -auto-approve
                    """

                }

            }

        }

        stage('Terraform Init') {

            steps {

                dir("${INFRA_DIR}") {

                    sh """
                    terraform init \
                    -backend-config=../backend/${params.ENV}.hcl \
                    -reconfigure
                    """

                }

            }

        }

        stage('Workspace') {

            steps {

                dir("${INFRA_DIR}") {

                    sh """
                    terraform workspace select ${params.ENV} || terraform workspace new ${params.ENV}
                    """

                }

            }

        }

        stage('Validate') {

            steps {

                dir("${INFRA_DIR}") {

                    sh '''
                    terraform validate
                    terraform fmt -check
                    '''

                }

            }

        }

        stage('Terraform Plan') {

            when {

                anyOf {

                    expression { params.ACTION=="plan" }
                    expression { params.ACTION=="apply" }

                }

            }

            steps {

                dir("${INFRA_DIR}") {

                    sh """
                    terraform plan \
                    -var-file=terraform.tfvars \
                    -out=tfplan
                    """

                }

            }

        }

        stage('Approval') {

            when {

                expression {

                    params.ACTION=="apply"

                }

            }

            steps {

                input "Deploy ${params.ENV} Infrastructure?"

            }

        }

        stage('Terraform Apply') {

            when {

                expression {

                    params.ACTION=="apply"

                }

            }

            steps {

                dir("${INFRA_DIR}") {

                    sh '''
                    terraform apply -auto-approve tfplan
                    '''

                }

            }

        }

        stage('Terraform Destroy') {

            when {

                expression {

                    params.ACTION=="destroy"

                }

            }

            steps {

                dir("${INFRA_DIR}") {

                    sh """
                    terraform destroy \
                    -auto-approve \
                    -var-file=terraform.tfvars
                    """

                }

            }

        }

    }

    post {

        success {

            echo "Deployment Successful"

            // Uncomment after Slack Plugin installation
            /*
            slackSend(
                channel: '#terraform-jenkins',
                color: 'good',
                message: "SUCCESS : ${params.ACTION} completed for ${params.ENV}"
            )
            */

        }

        failure {

            echo "Deployment Failed"

            /*
            slackSend(
                channel: '#terraform-jenkins',
                color: 'danger',
                message: "FAILED : ${params.ACTION} for ${params.ENV}"
            )
            */

        }

        always {

            archiveArtifacts artifacts: '**/tfplan', allowEmptyArchive: true
            deleteDir()

        }

    }

}